apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: litmuschaos
  pass_credentials_all: false
  password: ""
  url: https://litmuschaos.github.io/litmus-helm/
  username: ""
